### ISSUE TITLE
How to translate cookie Text?

### ISSUE THREAD

**Issue by StanBarrows** [onicial/laravel-bulma-notifications#15]
How to translate cookie Text?

![image](https://user-images.githubusercontent.com/10268813/56091171-8842ab80-5eab-11e9-9fb7-54d4dfac30ff.png)

![image](https://user-images.githubusercontent.com/10268813/56091177-92fd4080-5eab-11e9-9b7d-1934b85e766b.png)

![image](https://user-images.githubusercontent.com/10268813/56091183-a14b5c80-5eab-11e9-8561-50dbe087dc39.png)

**Comment by mhetreramesh** [comment]
Now you can just add translatable text in your config files.
